In [81]:
# (a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

import numpy as np
arr = np.array([1,2,3,6,4,5])
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [82]:
# (b) Flatten the NumPy array

array1 = np.array([[1,2,3], [2,4,6] , [1,2,3]])
flattened = array1.flatten()
print(flattened)


[1 2 3 2 4 6 1 2 3]


In [83]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison1 = arr1 == arr2
comparison2 = arr1 < arr2
print(comparison1)
print(comparison2)

[[ True  True]
 [ True  True]]
[[False False]
 [False False]]


In [84]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
x_freq = np.bincount(x).argmax()
x_indices = np.where(x == x_freq)
print(x_freq)
print(x_indices)
y = np.array([1,1,1,2,3,4,2,4,3,3])
y_freq = np.bincount(y).argmax()
y_indices = np.where(y == y_freq)
print(y_freq)
print(y_indices)


1
(array([0, 5, 7, 8, 9]),)
1
(array([0, 1, 2]),)


In [85]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
sum_all = gfg.sum()
sum_row = gfg.sum(axis=1)
sum_col = gfg.sum(axis=0)
print(sum_all)
print(sum_row)
print(sum_col)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [86]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum = np.trace(n_array)
eig_vals, eig_vecs = np.linalg.eig(n_array)
inverse = np.linalg.inv(n_array)
det = np.linalg.det(n_array)
print(diag_sum)
print(eig_vals)
print(eig_vecs)
print(inverse)
print(det)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [87]:
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
cov1 = np.cov(np.array(p1).T, np.array(q1).T)
print(product1)
print(cov1)

p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
combined = np.hstack((p2, q2.T))
cov2 = np.cov(combined.T)
print(product2)
print(cov2)

[[16 19]
 [26 31]]
[[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [88]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner = np.inner(x, y)
outer = np.outer(x, y)
cartesian = np.array([[i, j] for i in x.flatten() for j in y.flatten()])
print(inner)
print(outer)
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [89]:
array = np.array([[1, -2, 3], [-4, 5, -6]])
abs_array = np.abs(array)
print(abs_array)

[[1 2 3]
 [4 5 6]]


In [90]:
flat = array.flatten()
percentile_flat = np.percentile(flat, [25, 50, 75])
percentile_col = np.percentile(array, [25, 50, 75], axis=0)
percentile_row = np.percentile(array, [25, 50, 75], axis=1)
print(percentile_flat)
print(percentile_col)
print(percentile_row)

[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [91]:
mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)
print(mean_flat)
print(median_flat)
print(std_flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)
print(mean_col)
print(median_col)
print(std_col)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)
print(mean_row)
print(median_row)
print(std_row)

-0.5
-0.5
3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [93]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
floor = np.floor(a)
ceil = np.ceil(a)
truncated = np.trunc(a)
rounded = np.round(a)
print(floor)
print(ceil)
print(truncated)
print(rounded)

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [94]:
array = np.array([10,52,62,16,16,54,453])
sorted_array = np.sort(array)
sorted_indices = np.argsort(array)
smallest_4th = np.sort(array)[:4]
largest_5th = np.sort(array)[-5:]
print(sorted_array)
print(sorted_indices)
print(smallest_4th)
print(largest_5th)

[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [100]:
array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
integer_element = array[array == array.astype(int)]
print(integer_element)
float_element = array[array != array.astype(int)]
print(float_element)

[1. 2. 3. 2.]
[1.2 2.2]


<img src ="IMG_7504.jpg"/>

In [101]:
import numpy as np
from PIL import Image

def img_to_array(path, save_path="image_array.txt"):
    img = Image.open(path)
    img_array = np.array(img)

    if len(img_array.shape) == 2:
        print("Grayscale image detected.")
        reshaped_array = img_array.reshape(-1, 1)
    elif len(img_array.shape) == 3 and img_array.shape[2] == 3:
        print("RGB image detected.")
        reshaped_array = img_array.reshape(-1, 3)
    else:
        print("Unsupported image format.")
        return

    np.savetxt(save_path, reshaped_array, fmt='%d')
    print(f"Image array saved to {save_path}")


In [102]:
def load_image_array_from_file(file_path):
    data = np.loadtxt(file_path, dtype=int)
    return data
